name: Run Script

on:
  pull_request:
    branches:
      - main  # or whatever your default branch is
  push:
    branches:
      - test

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          python diffAnalyzer.py ${{ github.event.pull_request.head.sha }} >> $GITHUB_STEP_SUMMARY
        else
          python diffAnalyzer.py HEAD >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Process feedback
      if: always()
      run: |
        if [ -f "code_review_annotations.txt" ]; then
          while IFS= read -r line; do
            echo "$line"
          done < "code_review_annotations.txt"
        fi
        