name: Run Script

on:
  issue_comment:
    types: [created, edited]

jobs:
  run-script:
    if: |
      github.event_name == 'issue_comment' && 
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      
    steps:
    - name: Get PR details
      id: pr
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const prNumber = context.payload.issue.number;
          const { data: pr } = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: prNumber
          });
          return {
            head_ref: pr.head.ref,
            head_sha: pr.head.sha,
            base_sha: pr.base.sha
          }
        
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ fromJSON(steps.pr.outputs.result).head_sha }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python diffAnalyzer.py ${{ fromJSON(steps.pr.outputs.result).head_sha }}
        
    - name: Process annotations
      if: always()
      run: |
        while IFS= read -r line; do
          if [[ $line == "::notice"* ]] || [[ $line == "::warning"* ]]; then
            echo "$line"
          fi
        done < output.txt
        