name: Run Script

on:
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          python diffAnalyzer.py ${{ github.event.pull_request.head.sha }} | tee output.txt
        else
          python diffAnalyzer.py HEAD | tee output.txt
        fi
        cat output.txt >> $GITHUB_STEP_SUMMARY
        
    - name: Process annotations
      if: always()
      run: |
        while IFS= read -r line; do
          if [[ $line == "::notice"* ]] || [[ $line == "::warning"* ]]; then
            echo "$line"
          fi
        done < output.txt
        